/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VizsgatippekRouteImport } from './routes/vizsgatippek'
import { Route as VelemenyekRouteImport } from './routes/velemenyek'
import { Route as TestepermisRouteImport } from './routes/testepermis'
import { Route as SzolgaltatasokRouteImport } from './routes/szolgaltatasok'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SikereinkRouteImport } from './routes/sikereink'
import { Route as RolunkRouteImport } from './routes/rolunk'
import { Route as OktatokRouteImport } from './routes/oktatok'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as KapcsolatRouteImport } from './routes/kapcsolat'
import { Route as JelentkezesRouteImport } from './routes/jelentkezes'
import { Route as HirekRouteImport } from './routes/hirek'
import { Route as GyikRouteImport } from './routes/gyik'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media/$'

const VizsgatippekRoute = VizsgatippekRouteImport.update({
  id: '/vizsgatippek',
  path: '/vizsgatippek',
  getParentRoute: () => rootRouteImport,
} as any)
const VelemenyekRoute = VelemenyekRouteImport.update({
  id: '/velemenyek',
  path: '/velemenyek',
  getParentRoute: () => rootRouteImport,
} as any)
const TestepermisRoute = TestepermisRouteImport.update({
  id: '/testepermis',
  path: '/testepermis',
  getParentRoute: () => rootRouteImport,
} as any)
const SzolgaltatasokRoute = SzolgaltatasokRouteImport.update({
  id: '/szolgaltatasok',
  path: '/szolgaltatasok',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SikereinkRoute = SikereinkRouteImport.update({
  id: '/sikereink',
  path: '/sikereink',
  getParentRoute: () => rootRouteImport,
} as any)
const RolunkRoute = RolunkRouteImport.update({
  id: '/rolunk',
  path: '/rolunk',
  getParentRoute: () => rootRouteImport,
} as any)
const OktatokRoute = OktatokRouteImport.update({
  id: '/oktatok',
  path: '/oktatok',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const KapcsolatRoute = KapcsolatRouteImport.update({
  id: '/kapcsolat',
  path: '/kapcsolat',
  getParentRoute: () => rootRouteImport,
} as any)
const JelentkezesRoute = JelentkezesRouteImport.update({
  id: '/jelentkezes',
  path: '/jelentkezes',
  getParentRoute: () => rootRouteImport,
} as any)
const HirekRoute = HirekRouteImport.update({
  id: '/hirek',
  path: '/hirek',
  getParentRoute: () => rootRouteImport,
} as any)
const GyikRoute = GyikRouteImport.update({
  id: '/gyik',
  path: '/gyik',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gyik': typeof GyikRoute
  '/hirek': typeof HirekRoute
  '/jelentkezes': typeof JelentkezesRoute
  '/kapcsolat': typeof KapcsolatRoute
  '/mcp': typeof McpRoute
  '/oktatok': typeof OktatokRoute
  '/rolunk': typeof RolunkRoute
  '/sikereink': typeof SikereinkRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/szolgaltatasok': typeof SzolgaltatasokRoute
  '/testepermis': typeof TestepermisRoute
  '/velemenyek': typeof VelemenyekRoute
  '/vizsgatippek': typeof VizsgatippekRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gyik': typeof GyikRoute
  '/hirek': typeof HirekRoute
  '/jelentkezes': typeof JelentkezesRoute
  '/kapcsolat': typeof KapcsolatRoute
  '/mcp': typeof McpRoute
  '/oktatok': typeof OktatokRoute
  '/rolunk': typeof RolunkRoute
  '/sikereink': typeof SikereinkRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/szolgaltatasok': typeof SzolgaltatasokRoute
  '/testepermis': typeof TestepermisRoute
  '/velemenyek': typeof VelemenyekRoute
  '/vizsgatippek': typeof VizsgatippekRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gyik': typeof GyikRoute
  '/hirek': typeof HirekRoute
  '/jelentkezes': typeof JelentkezesRoute
  '/kapcsolat': typeof KapcsolatRoute
  '/mcp': typeof McpRoute
  '/oktatok': typeof OktatokRoute
  '/rolunk': typeof RolunkRoute
  '/sikereink': typeof SikereinkRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/szolgaltatasok': typeof SzolgaltatasokRoute
  '/testepermis': typeof TestepermisRoute
  '/velemenyek': typeof VelemenyekRoute
  '/vizsgatippek': typeof VizsgatippekRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gyik'
    | '/hirek'
    | '/jelentkezes'
    | '/kapcsolat'
    | '/mcp'
    | '/oktatok'
    | '/rolunk'
    | '/sikereink'
    | '/sitemap.xml'
    | '/szolgaltatasok'
    | '/testepermis'
    | '/velemenyek'
    | '/vizsgatippek'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/media/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gyik'
    | '/hirek'
    | '/jelentkezes'
    | '/kapcsolat'
    | '/mcp'
    | '/oktatok'
    | '/rolunk'
    | '/sikereink'
    | '/sitemap.xml'
    | '/szolgaltatasok'
    | '/testepermis'
    | '/velemenyek'
    | '/vizsgatippek'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/media/$'
  id:
    | '__root__'
    | '/'
    | '/gyik'
    | '/hirek'
    | '/jelentkezes'
    | '/kapcsolat'
    | '/mcp'
    | '/oktatok'
    | '/rolunk'
    | '/sikereink'
    | '/sitemap.xml'
    | '/szolgaltatasok'
    | '/testepermis'
    | '/velemenyek'
    | '/vizsgatippek'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/media/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GyikRoute: typeof GyikRoute
  HirekRoute: typeof HirekRoute
  JelentkezesRoute: typeof JelentkezesRoute
  KapcsolatRoute: typeof KapcsolatRoute
  McpRoute: typeof McpRoute
  OktatokRoute: typeof OktatokRoute
  RolunkRoute: typeof RolunkRoute
  SikereinkRoute: typeof SikereinkRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SzolgaltatasokRoute: typeof SzolgaltatasokRoute
  TestepermisRoute: typeof TestepermisRoute
  VelemenyekRoute: typeof VelemenyekRoute
  VizsgatippekRoute: typeof VizsgatippekRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vizsgatippek': {
      id: '/vizsgatippek'
      path: '/vizsgatippek'
      fullPath: '/vizsgatippek'
      preLoaderRoute: typeof VizsgatippekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/velemenyek': {
      id: '/velemenyek'
      path: '/velemenyek'
      fullPath: '/velemenyek'
      preLoaderRoute: typeof VelemenyekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testepermis': {
      id: '/testepermis'
      path: '/testepermis'
      fullPath: '/testepermis'
      preLoaderRoute: typeof TestepermisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/szolgaltatasok': {
      id: '/szolgaltatasok'
      path: '/szolgaltatasok'
      fullPath: '/szolgaltatasok'
      preLoaderRoute: typeof SzolgaltatasokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sikereink': {
      id: '/sikereink'
      path: '/sikereink'
      fullPath: '/sikereink'
      preLoaderRoute: typeof SikereinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rolunk': {
      id: '/rolunk'
      path: '/rolunk'
      fullPath: '/rolunk'
      preLoaderRoute: typeof RolunkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oktatok': {
      id: '/oktatok'
      path: '/oktatok'
      fullPath: '/oktatok'
      preLoaderRoute: typeof OktatokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kapcsolat': {
      id: '/kapcsolat'
      path: '/kapcsolat'
      fullPath: '/kapcsolat'
      preLoaderRoute: typeof KapcsolatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jelentkezes': {
      id: '/jelentkezes'
      path: '/jelentkezes'
      fullPath: '/jelentkezes'
      preLoaderRoute: typeof JelentkezesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hirek': {
      id: '/hirek'
      path: '/hirek'
      fullPath: '/hirek'
      preLoaderRoute: typeof HirekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gyik': {
      id: '/gyik'
      path: '/gyik'
      fullPath: '/gyik'
      preLoaderRoute: typeof GyikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GyikRoute: GyikRoute,
  HirekRoute: HirekRoute,
  JelentkezesRoute: JelentkezesRoute,
  KapcsolatRoute: KapcsolatRoute,
  McpRoute: McpRoute,
  OktatokRoute: OktatokRoute,
  RolunkRoute: RolunkRoute,
  SikereinkRoute: SikereinkRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SzolgaltatasokRoute: SzolgaltatasokRoute,
  TestepermisRoute: TestepermisRoute,
  VelemenyekRoute: VelemenyekRoute,
  VizsgatippekRoute: VizsgatippekRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
